### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# install the libraries
# !pip install numpy

In [ ]:
# import into the notebook
import numpy

In [ ]:
# Check the version (12:19 IST 10-06-2025)
print(numpy.__version__)

2.2.5


#### np.array()
- Helps for creating array
- 1d, 2d, 3d array

In [126]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [127]:
a = np.array([1, 3, 9])
print(a)

[1 3 9]


In [128]:
a = np.array([[1, 2, 3],
             [2, 3, 4],
             [2, 4, 7]])
print(a)

[[1 2 3]
 [2 3 4]
 [2 4 7]]


In [129]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [130]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [131]:
c = np.array([[
              [1,2],
               [3,4]],

                 [[5,6],
                  [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [132]:
c = np.array([[[1, 2],
              [2, 4]],

             [[1, 3],
              [3, 7]]])
print(c)

[[[1 2]
  [2 4]]

 [[1 3]
  [3 7]]]


In [133]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [134]:
import numpy as np

#### np.arrange()

- It helps to creating a array within a value
- ( Start end step)

In [135]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [136]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
np.arange(11, 1, -3)

array([11,  8,  5,  2])

In [138]:
np.arange(1, 11, 2) #step = 2

array([1, 3, 5, 7, 9])

#### reshape(matrix, row, column)

In [139]:
np.arange(20).reshape(5, 4) # row, columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [140]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
np.arange(20).reshape(5, 2, 2) # matrix, row, col

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [142]:
np.arange(20).reshape(5, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [144]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

#### np.zeroes() & np.ones()

In [145]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [146]:
np.arange(20, dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [147]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [148]:
np.ones([43, 45])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(43, 45))

In [149]:
np.ones(20, dtype=np.float16)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.], dtype=float16)

In [150]:
np.ones(20, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [151]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
# np.random
np.random.random((3,4))

array([[0.66116196, 0.19445767, 0.39893696, 0.73101053],
       [0.34137148, 0.30662595, 0.41118852, 0.61105564],
       [0.36004237, 0.17807042, 0.19291342, 0.30261374]])

In [153]:
np.random.random((1, 2))

array([[0.18869382, 0.18180943]])

#### np.random()

In [165]:
np.random.rand(20).reshape(5, 2, 2)
# Use np.random.rand to generate random numbers
# then reshape to the desired dimensions (5, 2, 2).

array([[[0.33037185, 0.16510145],
        [0.92228453, 0.31991788]],

       [[0.82863138, 0.38594935],
        [0.09677247, 0.1812171 ]],

       [[0.33648719, 0.43796864],
        [0.60301159, 0.71469294]],

       [[0.01189882, 0.15401894],
        [0.60917207, 0.06231276]],

       [[0.27074818, 0.56871609],
        [0.441985  , 0.20377623]]])

In [164]:
import numpy as np

# Generate a single random float
random_float = np.random.random()
print("Single random float:", random_float)
print('--'*40)

# Generate an array of 5 random floats
random_array = np.random.random(size=5)
print("Array of 5 random floats:", random_array)
print('--'*40)

# Generate a 3x4 array of random floats
random_2d_array = np.random.random(size=(3, 4))
print("3x4 array of random floats:")
print(random_2d_array)


Single random float: 0.8159670080492666
--------------------------------------------------------------------------------
Array of 5 random floats: [0.42935352 0.50353684 0.70201896 0.27128877 0.70985476]
--------------------------------------------------------------------------------
3x4 array of random floats:
[[0.95758863 0.40799077 0.88698437 0.95856462]
 [0.02461547 0.6190502  0.29812177 0.70536561]
 [0.48937041 0.01678616 0.06621046 0.71644302]]


In [155]:
np.random.randint(1,100,(3,4))

array([[31, 78,  3, 78],
       [44, 18, 18, 25],
       [11, 42, 21, 85]], dtype=int32)

In [156]:
np.random.choice([1,2,3,4,])

np.int64(2)

In [157]:
np.random.choice([1,2,3,4,5,6], size=(2,2))
# Specify the 'size' argument within np.random.choice to
# directly generate an array with the desired shape (2, 2).

array([[6, 2],
       [1, 6]])

In [158]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### np.linspace()

In [159]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

#### np.identity()

In [160]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [40]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### ndim
- Help to check how many dimension 

In [42]:
# ndim
a3.ndim

3

#### shape

In [43]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### size
- How many element in their 

In [44]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

#### itmesize

In [168]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### itemsize

In [ ]:
# itemsize
a3.itemsize

8

#### dtype

In [46]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


#### Changing Datatype

In [47]:
a4 = np.arange(10, dtype = np.int16).reshape(2, 5)

a4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16)

In [48]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operations 

In [172]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

#### Relational Operations

In [51]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

#### Vector Operations

In [52]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

#### np.round()

In [53]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[29., 34., 29.],
       [75.,  4., 56.],
       [75., 27., 66.]])

In [54]:
a2 = np.random.random((2, 5))
a2 = np.round(a2 * 200)
a2

array([[ 64., 181.,  82., 194., 166.],
       [174.,   1.,  18.,  16.,  79.]])

#### np.isin()

In [ ]:
# Alternatively, if you want to find if any element in a2 is equal to 54 or 67:
np.isin(a2, [54, 67])


array([[False, False, False, False, False],
       [False, False, False, False, False]])

#### Comparison

In [55]:
# Assuming you want to compare the first two elements of each row of a2 with [54, 67]
a2[:, :2] == [54, 67]


array([[False, False],
       [False, False]])

In [ ]:
# Another way for element-wise comparison:
(a2 == 54) | (a2 == 67)  # Using element-wise OR for comparison

array([[False, False, False, False, False],
       [False, False, False, False, False]])

#### min/ max/ sum/ prod

In [58]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([163125.,   3672., 107184.])

#### mean/ median/ std/ var

In [59]:
# mean/median/std/var
np.var(a1,axis=1)

array([  5.55555556, 900.66666667, 434.        ])

#### trigonometric functions

In [60]:
# trigonometric functions
np.sin(a1)

array([[-0.66363388,  0.52908269, -0.66363388],
       [-0.38778164, -0.7568025 , -0.521551  ],
       [-0.38778164,  0.95637593, -0.02655115]])

#### np.dot()

In [61]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#### np.exp() / np.log()

In [179]:
np.log(a1)

C:\Users\Rudra\AppData\Local\Temp\ipykernel_10176\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [62]:
# log and exponents
np.exp(a1)

array([[3.93133430e+12, 5.83461743e+14, 3.93133430e+12],
       [3.73324200e+32, 5.45981500e+01, 2.09165950e+24],
       [3.73324200e+32, 5.32048241e+11, 4.60718663e+28]])

#### round/ floor/ ceil

In [2]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

NameError: name 'np' is not defined

### Indexing and Slicing

In [64]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### indexing

In [65]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
# starting from 0 row and col both
a2[0, 3] # row col

np.int64(3)

In [68]:
a2[1,0]

np.int64(4)

In [69]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
a3[1, 1, 1]

np.int64(7)

In [71]:
a3[1, 0]

array([4, 5])

In [72]:
a3[1,0,1]

np.int64(5)

In [73]:
a3[1,1,0]

np.int64(6)

In [74]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a1[0:5]

array([0, 1, 2, 3, 4])

In [76]:
a1[0:5:2]

array([0, 2, 4])

#### slicing

In [77]:
#slicing
a1[2:5:2]

array([2, 4])

In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
a2[0] # row

array([0, 1, 2, 3])

In [80]:
a2[0:2] # how many row start, end, steps

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
a2[0:2, 0:2] # after row, then slice the matrix

array([[0, 1],
       [4, 5]])

In [82]:
a2[0:2, :2]

array([[0, 1],
       [4, 5]])

In [83]:
a2[0:2, 1]

array([1, 5])

In [84]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [85]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [191]:
a2[::2, ::2]

array([[ 0,  2],
       [ 8, 10]])

In [87]:
a2[2]

array([ 8,  9, 10, 11])

In [88]:
a2[2, 1:3]

array([ 9, 10])

In [89]:
a2[2, :4:2]

array([ 8, 10])

In [90]:
a2[1,::3]

array([4, 7])

In [91]:
a2[0,:]

array([0, 1, 2, 3])

In [92]:
a2[:,2]

array([ 2,  6, 10])

In [93]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [94]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [96]:
a3[1, 0:-1, 1:]

array([[10, 11],
       [13, 14]])

In [97]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [98]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [99]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [100]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [103]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [104]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


#### np.nditer()

In [105]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

#### np.reshape()

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
# reshape
a2.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### np.transpose()

In [108]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [109]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### revel()

In [110]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [111]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(16, 32).reshape(4,4)
a5

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [112]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### np.hstack()

In [225]:
# np.hstack((a5, a4))

In [226]:
# np.hstack((a4,a5))

In [227]:
a6 = np.arange(16).reshape(4, 4)
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [228]:
np.hstack((a5, a6))

array([[16, 17, 18, 19,  0,  1,  2,  3],
       [20, 21, 22, 23,  4,  5,  6,  7],
       [24, 25, 26, 27,  8,  9, 10, 11],
       [28, 29, 30, 31, 12, 13, 14, 15]])

In [229]:
# np.hstack((a4, a6))

In [230]:
a8 = np.arange(12).reshape(4, 3)
a8

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [231]:
np.hstack((a8, a6))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13, 14, 15]])

#### np.vstack()

In [198]:
np.vstack((a5, a4))

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### Splitting

In [200]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### np.hsplit()

In [201]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [202]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [203]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [204]:
# np.hsplit(a4,5) 
# This show error 
# Because array split does not result in an equal division

In [205]:
# Vertical Stacking
a5

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

#### np.vsplit()

In [206]:
np.vsplit(a5, 2)

[array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [207]:
np.vsplit(a5,4)[0]

array([[16, 17, 18, 19]])

In [208]:
np.vsplit(a5,4)[0]

array([[16, 17, 18, 19]])