### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [74]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([69, 66,  3, 45, 34, 59, 34,  5, 46, 24, 89, 82, 88, 10, 88],
      dtype=int32)

In [75]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[38, 13, 63,  6],
       [ 7, 72, 86, 16],
       [74, 61,  2,  6],
       [63, 65, 38, 99],
       [18, 80, 36, 45],
       [93, 36, 62, 47]], dtype=int32)

In [76]:
c = np.random.randint(200, 10000, 36).reshape(6, 6)
c

array([[2006, 1162, 3491, 3395, 4916, 1844],
       [3754, 3440, 2672, 3486, 7782, 3775],
       [5383, 7598, 8867, 4977, 8090, 1901],
       [5484, 3460, 6731, 1093, 7966, 7943],
       [2443, 2851, 9223, 3988, 2652, 1176],
       [2804,  295, 6892, 2009, 6339, 8721]], dtype=int32)

In [77]:
np.sort(c)[0] # row wise default

array([1162, 1844, 2006, 3395, 3491, 4916], dtype=int32)

In [78]:
c == [1652, 2838, 4216, 5071, 5420, 5770]

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [79]:
np.sort(c, axis=0)

array([[2006,  295, 2672, 1093, 2652, 1176],
       [2443, 1162, 3491, 2009, 4916, 1844],
       [2804, 2851, 6731, 3395, 6339, 1901],
       [3754, 3440, 6892, 3486, 7782, 3775],
       [5383, 3460, 8867, 3988, 7966, 7943],
       [5484, 7598, 9223, 4977, 8090, 8721]], dtype=int32)

In [80]:
c[:, 0]

array([2006, 3754, 5383, 5484, 2443, 2804], dtype=int32)

In [81]:
a

array([69, 66,  3, 45, 34, 59, 34,  5, 46, 24, 89, 82, 88, 10, 88],
      dtype=int32)

In [82]:
np.sort(a)[::-1]

array([89, 88, 88, 82, 69, 66, 59, 46, 45, 34, 34, 24, 10,  5,  3],
      dtype=int32)

In [10]:
np.sort(b,axis=0)

array([[39,  4,  4,  1],
       [41, 24, 21, 56],
       [49, 37, 25, 66],
       [53, 57, 45, 74],
       [57, 60, 60, 77],
       [92, 65, 62, 93]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [83]:
a

array([69, 66,  3, 45, 34, 59, 34,  5, 46, 24, 89, 82, 88, 10, 88],
      dtype=int32)

In [87]:
# code
np.append(a,200)

array([ 69,  66,   3,  45,  34,  59,  34,   5,  46,  24,  89,  82,  88,
        10,  88, 200])

In [12]:
b

array([[49, 65, 25, 56],
       [92, 37, 60, 74],
       [39, 24, 62, 66],
       [53,  4,  4,  1],
       [41, 60, 45, 77],
       [57, 57, 21, 93]], dtype=int32)

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[49.        , 65.        , 25.        , 56.        ,  0.84384652],
       [92.        , 37.        , 60.        , 74.        ,  0.28752926],
       [39.        , 24.        , 62.        , 66.        ,  0.22729188],
       [53.        ,  4.        ,  4.        ,  1.        ,  0.37616069],
       [41.        , 60.        , 45.        , 77.        ,  0.21546975],
       [57.        , 57.        , 21.        , 93.        ,  0.55435537]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c, "\n -")
print(d)

[[0 1 2]
 [3 4 5]] 
 -
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [17]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [89]:
np.expand_dims(a,axis=1)

array([[69],
       [66],
       [ 3],
       [45],
       [34],
       [59],
       [34],
       [ 5],
       [46],
       [24],
       [89],
       [82],
       [88],
       [10],
       [88]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  4,  5,  7,  9, 11, 12, 13, 14]),)

In [23]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 2, 47,  9,  0,  0,  0, 19,  0,  4,  0,  8,  0,  0,  0,  0],
      dtype=int32)

In [24]:
np.where(a%2 == 0,0,a)

array([ 0, 47,  9, 85, 53,  0, 19, 91,  0,  0,  0, 65, 71,  0,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [25]:
# code
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [26]:
np.argmax(a)

np.int64(13)

In [27]:
b

array([[49, 65, 25, 56],
       [92, 37, 60, 74],
       [39, 24, 62, 66],
       [53,  4,  4,  1],
       [41, 60, 45, 77],
       [57, 57, 21, 93]], dtype=int32)

In [28]:
np.argmax(b,axis=0)

array([1, 0, 2, 5])

In [29]:
np.argmax(b,axis=1)

array([1, 0, 3, 0, 3, 3])

In [30]:
# np.argmin
np.argmin(a)

np.int64(0)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [31]:
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [32]:
np.cumsum(a)

array([  2,  49,  58, 143, 196, 284, 303, 394, 398, 458, 466, 531, 602,
       696, 750])

In [33]:
b

array([[49, 65, 25, 56],
       [92, 37, 60, 74],
       [39, 24, 62, 66],
       [53,  4,  4,  1],
       [41, 60, 45, 77],
       [57, 57, 21, 93]], dtype=int32)

In [34]:
np.cumsum(b,axis=1)

array([[ 49, 114, 139, 195],
       [ 92, 129, 189, 263],
       [ 39,  63, 125, 191],
       [ 53,  57,  61,  62],
       [ 41, 101, 146, 223],
       [ 57, 114, 135, 228]])

In [35]:
np.cumsum(b)

array([  49,  114,  139,  195,  287,  324,  384,  458,  497,  521,  583,
        649,  702,  706,  710,  711,  752,  812,  857,  934,  991, 1048,
       1069, 1162])

In [36]:
# np.cumprod
np.cumprod(a)

array([                   2,                   94,                  846,
                      71910,              3811230,            335388240,
                 6372376560,         579886266960,        2319545067840,
            139172704070400,     1113381632563200,    72369806116608000,
        5138256234279168000,  3380740105793449984, -1907475024249217024])

In [37]:
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [38]:
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [39]:
np.percentile(a,50)

np.float64(54.0)

In [40]:
np.median(a)

np.float64(54.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [41]:
# code
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [42]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [43]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [44]:
# code
a


array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [45]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [46]:
# code
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [47]:
np.flip(a)

array([54, 94, 71, 65,  8, 60,  4, 91, 19, 88, 53, 85,  9, 47,  2],
      dtype=int32)

In [48]:
b

array([[49, 65, 25, 56],
       [92, 37, 60, 74],
       [39, 24, 62, 66],
       [53,  4,  4,  1],
       [41, 60, 45, 77],
       [57, 57, 21, 93]], dtype=int32)

In [49]:
np.flip(b,axis=1)

array([[56, 25, 65, 49],
       [74, 60, 37, 92],
       [66, 62, 24, 39],
       [ 1,  4,  4, 53],
       [77, 45, 60, 41],
       [93, 21, 57, 57]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [50]:
# code
a

array([ 2, 47,  9, 85, 53, 88, 19, 91,  4, 60,  8, 65, 71, 94, 54],
      dtype=int32)

In [51]:
np.put(a, [0, 1], [100, 200], mode='raise')

In [52]:
a

array([100, 200,   9,  85,  53,  88,  19,  91,   4,  60,   8,  65,  71,
        94,  54], dtype=int32)

In [53]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [54]:
# code
a

array([110, 530,   9,  85,  53,  88,  19,  91,   4,  60,   8,  65,  71,
        94,  54], dtype=int32)

In [55]:
np.delete(a,[0,2,4])

array([530,  85,  88,  19,  91,   4,  60,   8,  65,  71,  94,  54],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [56]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m,n)

array([3, 4, 5])

In [58]:
np.setdiff1d(n,m)

array([6, 7])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,1)]

C:\Users\Rudra\AppData\Local\Temp\ipykernel_19416\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [92]:
# code
a

array([1, 2, 3])

In [93]:
np.clip(a,a_min=25,a_max=75)

array([25, 25, 25])

# np.swapaxes

In [2]:
# Create a 2x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Swap axes 0 and 1 (rows and columns)
swapped = np.swapaxes(arr, 0, 1)

print("Original:\n", arr)
print("Swapped:\n", swapped)


Original:
 [[1 2 3]
 [4 5 6]]
Swapped:
 [[1 4]
 [2 5]
 [3 6]]


# np.uniform

In [3]:
# Generate 5 random numbers between 0 and 1
random_numbers = np.random.uniform(0, 1, 5)

print("Random numbers:", random_numbers)


Random numbers: [0.2614129  0.46183762 0.42822502 0.93290325 0.77309219]


# np.count_nonzero

In [97]:
import numpy as np

# Create an example array
my_array = np.array([0, 1, 2, 0, 3, 0])

# Count the non-zero elements
non_zero_count = np.count_nonzero(my_array)
non_zero_count
# Print the result
# The variable non_zero_count will hold the value 3
# as there are 3 non-zero elements in my_array ([1,2,3])

3

-  https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

- https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

# title

In [98]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [99]:
import numpy as np

arr = np.array([1, 2, 3])
repeated_arr = np.tile(arr, 3)  # Repeat 'arr' 3 times
print(repeated_arr)  # Output: [1 2 3 1 2 3 1 2 3]

[1 2 3 1 2 3 1 2 3]


In [100]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

#  np.allclose and equals

In [102]:
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.00001, 2.0, 3.0])

# Using default tolerances (rtol=1e-05, atol=1e-08)
print(np.allclose(a, b))  # Likely True due to small difference

True


In [103]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 3.00001])

# print(np.equals(a, b))  # True
# print(np.equals(a, c))  # False, due to the tiny difference in the last element